import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/cn";
import { TooltipProvider } from "@/packages/components/overlay/tooltip";
import { Toaster } from "@/packages/components/feedback/sonner";
import { MobileNav } from "@/ui/layout/mobile-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterSans = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  preload: true,
  style: "normal",
  subsets: ["vietnamese", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("antialiased", InterSans.className)}
        suppressHydrationWarning
      >
        <TooltipProvider delayDuration={50}>
          {children}
          <MobileNav />
        </TooltipProvider>
        <Toaster duration={3000} position="bottom-right" />
      </body>
    </html>
  );
}
